import React, { useState } from 'react';
import {
  CheckCircle2,
  Calendar,
  FileText,
  AlertTriangle,
  ShieldCheck,
  Volume2,
  VolumeX,
  Copy,
  Printer,
  CalendarPlus,
  Send,
  Building,
  ExternalLink,
  Phone,
  Mail,
  MapPin,
  Clock,
  HelpCircle,
  Sparkles,
  Info,
  CheckSquare,
  Square,
  ChevronRight,
  ShieldAlert,
} from 'lucide-react';
import { NoticeAnalysis, LanguageCode, NoticeDeadline } from '../types/notice';
import { UI_TRANSLATIONS } from '../utils/translations';
import { speechController } from '../utils/speech';
import { downloadCalendarEvent } from '../utils/calendar';

interface AnalysisViewProps {
  analysis: NoticeAnalysis;
  language: LanguageCode;
  originalImage: string | null;
  onInspectImage: () => void;
  selectedModel: string;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({
  analysis,
  language,
  originalImage,
  onInspectImage,
  selectedModel,
}) => {
  const t = UI_TRANSLATIONS[language];
  const [activeTab, setActiveTab] = useState<
    'overview' | 'checklist' | 'deadlines' | 'documents' | 'eligibility' | 'missing' | 'trust' | 'qa'
  >('overview');
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [completedSteps, setCompletedSteps] = useState<Record<number, boolean>>({});
  const [copyFeedback, setCopyFeedback] = useState(false);

  // Q&A state
  const [qaQuestion, setQaQuestion] = useState('');
  const [qaLoading, setQaLoading] = useState(false);
  const [qaHistory, setQaHistory] = useState<Array<{ q: string; a: string; time: string }>>([]);

  const toggleStep = (stepNumber: number) => {
    setCompletedSteps((prev) => ({
      ...prev,
      [stepNumber]: !prev[stepNumber],
    }));
  };

  const handleToggleAudio = () => {
    if (isPlayingAudio) {
      speechController.stop();
      setIsPlayingAudio(false);
    } else {
      const narrationText = `${analysis.title}. Issued by ${analysis.issuingOrganization.name}. ${analysis.plainSummary}.`;
      speechController.speak(narrationText, language, (speaking) => {
        setIsPlayingAudio(speaking);
      });
    }
  };

  const handleCopyChecklist = () => {
    const lines = [
      `ACTION PLAN: ${analysis.title}`,
      `Authority: ${analysis.issuingOrganization.name}`,
      `Reference: ${analysis.referenceNumber} | Date: ${analysis.noticeDate}`,
      '',
      'KEY DEADLINES:',
      ...analysis.deadlines.map((d) => `- ${d.label}: ${d.date} (${d.urgency})`),
      '',
      'ACTION STEPS:',
      ...analysis.actionChecklist.map(
        (s) => `[${completedSteps[s.stepNumber] ? 'X' : ' '}] Step ${s.stepNumber}: ${s.title} - ${s.description}`
      ),
      '',
      'REQUIRED DOCUMENTS:',
      ...analysis.requiredDocuments.map((doc) => `- ${doc.documentName} (${doc.mandatory ? 'Mandatory' : 'Optional'})`),
      '',
      'Helpline: ' + (analysis.contactDetails.helplinePhone || 'Check notice'),
      'Generated by NammaNotice AI (Gemma 4 Multimodal)',
    ].join('\n');

    navigator.clipboard.writeText(lines);
    setCopyFeedback(true);
    setTimeout(() => setCopyFeedback(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCalendarExport = (deadline: NoticeDeadline) => {
    downloadCalendarEvent(analysis.title, deadline, analysis.issuingOrganization.name);
  };

  const handleAskQuestion = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!qaQuestion.trim() || qaLoading) return;

    const userQ = qaQuestion.trim();
    setQaQuestion('');
    setQaLoading(true);

    try {
      const res = await fetch('/api/ask-notice', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          imageBase64: originalImage,
          question: userQ,
          language,
          selectedModel,
        }),
      });

      const data = await res.json();
      if (data.success) {
        setQaHistory((prev) => [
          ...prev,
          {
            q: userQ,
            a: data.answer,
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
      } else {
        setQaHistory((prev) => [
          ...prev,
          {
            q: userQ,
            a: 'Error processing question: ' + (data.error || 'Please try again.'),
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
      }
    } catch (err: any) {
      setQaHistory((prev) => [
        ...prev,
        {
          q: userQ,
          a: 'Network error communicating with server: ' + err.message,
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
    } finally {
      setQaLoading(false);
    }
  };

  const completedCount = Object.values(completedSteps).filter(Boolean).length;
  const totalSteps = analysis.actionChecklist.length;
  const progressPercent = totalSteps > 0 ? Math.round((completedCount / totalSteps) * 100) : 0;

  return (
    <div className="w-full space-y-6">
      {/* Notice Header Hero Banner */}
      <div className="bg-white rounded-2xl border border-slate-200/90 p-5 sm:p-6 shadow-xs">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div>
            <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500 mb-1.5">
              <span className="font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded border border-amber-200/60 uppercase tracking-wide">
                {analysis.category.replace('_', ' ')}
              </span>
              <span>·</span>
              <span className="font-medium text-slate-700 flex items-center gap-1">
                <Building className="w-3.5 h-3.5 text-slate-400" />
                {analysis.issuingOrganization.name}
              </span>
              <span>·</span>
              <span>Ref: {analysis.referenceNumber}</span>
              <span>·</span>
              <span>Dated: {analysis.noticeDate}</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900">
              {analysis.title}
            </h2>
            {analysis.originalTitle && analysis.originalTitle !== analysis.title && (
              <p className="text-xs text-slate-500 mt-1 italic">
                Original Text: {analysis.originalTitle}
              </p>
            )}
          </div>

          {/* Quick Actions (Audio Narration, Print, Copy) */}
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={handleToggleAudio}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all ${
                isPlayingAudio
                  ? 'bg-rose-100 text-rose-800 border border-rose-300 animate-pulse'
                  : 'bg-amber-50 hover:bg-amber-100 text-amber-900 border border-amber-200'
              }`}
            >
              {isPlayingAudio ? (
                <>
                  <VolumeX className="w-4 h-4 text-rose-600" />
                  <span>{t.stopAudio}</span>
                </>
              ) : (
                <>
                  <Volume2 className="w-4 h-4 text-amber-700" />
                  <span>{t.listenSummary}</span>
                </>
              )}
            </button>

            <button
              onClick={handleCopyChecklist}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>{copyFeedback ? t.checklistCopied : t.copyChecklist}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>{t.printReport}</span>
            </button>

            {originalImage && (
              <button
                onClick={onInspectImage}
                className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium border border-slate-300 hover:bg-slate-50 text-slate-800 transition-colors"
              >
                <FileText className="w-3.5 h-3.5 text-slate-500" />
                <span>Original Notice</span>
              </button>
            )}
          </div>
        </div>

        {/* Forensic Authenticity & Trust Badges Strip */}
        <div className="mt-4 pt-3 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-1.5 text-slate-700">
              <ShieldCheck
                className={`w-4 h-4 ${
                  analysis.trustAndSafety.sealDetected ? 'text-emerald-600' : 'text-slate-400'
                }`}
              />
              <span className="font-medium">
                {analysis.trustAndSafety.sealDetected
                  ? `Seal: ${analysis.trustAndSafety.sealDetails || 'Detected'}`
                  : 'Official Seal: Not Visible'}
              </span>
            </div>

            <span className="text-slate-300">·</span>

            <div className="flex items-center gap-1.5 text-slate-700">
              <CheckCircle2
                className={`w-4 h-4 ${
                  analysis.trustAndSafety.signatureDetected ? 'text-emerald-600' : 'text-slate-400'
                }`}
              />
              <span className="font-medium">
                {analysis.trustAndSafety.signatureDetected
                  ? `Signatory: ${analysis.trustAndSafety.signatoryDesignation || 'Verified'}`
                  : 'Signature: Not Visible'}
              </span>
            </div>

            <span className="text-slate-300">·</span>

            <div className="flex items-center gap-1 text-slate-600">
              <span>Confidence:</span>
              <span className="font-bold text-emerald-700">
                {analysis.trustAndSafety.confidenceScore}%
              </span>
            </div>
          </div>

          <div className="text-[11px] text-slate-500">
            Decoded by <span className="font-semibold text-slate-700">Gemma 4</span> ({selectedModel})
          </div>
        </div>
      </div>

      {/* Missing or Unreadable Information Warning Banner (Trust & Safety Requirement) */}
      {analysis.missingOrUnreadableInfo && analysis.missingOrUnreadableInfo.length > 0 && (
        <div className="rounded-xl bg-amber-50/90 border border-amber-300/80 p-4">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <h4 className="text-xs font-bold text-amber-900 uppercase tracking-wide">
                {t.missingAlertTitle}
              </h4>
              <p className="text-xs text-amber-800 mt-0.5">
                {t.missingAlertDesc}
              </p>
              <div className="mt-2.5 grid grid-cols-1 md:grid-cols-2 gap-2">
                {analysis.missingOrUnreadableInfo.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-2.5 rounded-lg bg-white/80 border border-amber-200 text-xs"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-bold text-slate-900">{item.item}</span>
                      <span className="text-[10px] font-semibold text-rose-700 bg-rose-50 px-1.5 py-0.5 rounded uppercase">
                        {item.status.replace('_', ' ')}
                      </span>
                    </div>
                    <p className="text-slate-600 mb-1">{item.explanation}</p>
                    <p className="text-[11px] font-medium text-amber-900">
                      Recommendation: {item.recommendedAction}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Navigation Segmented Tabs */}
      <div className="flex items-center gap-1 overflow-x-auto pb-1 p-1 bg-slate-100 rounded-xl border border-slate-200">
        {[
          { id: 'overview', label: t.overviewTab, icon: FileText },
          { id: 'checklist', label: `${t.actionChecklistTab} (${completedCount}/${totalSteps})`, icon: CheckSquare },
          { id: 'deadlines', label: t.deadlinesTab, icon: Calendar },
          { id: 'documents', label: t.documentsTab, icon: FileText },
          { id: 'eligibility', label: t.eligibilityTab, icon: Info },
          { id: 'trust', label: t.trustSafetyTab, icon: ShieldCheck },
          { id: 'qa', label: t.askAiTab, icon: HelpCircle },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${
                isActive
                  ? 'bg-white text-slate-900 shadow-xs'
                  : 'text-slate-600 hover:text-slate-900 hover:bg-white/50'
              }`}
            >
              <Icon className={`w-3.5 h-3.5 ${isActive ? 'text-amber-700' : 'text-slate-400'}`} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Panels */}

      {/* 1. OVERVIEW TAB */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-2">
              Plain-Language Explanation
            </h3>
            <p className="text-base text-slate-800 leading-relaxed font-medium">
              {analysis.plainSummary}
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6 pt-6 border-t border-slate-100">
              <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80">
                <span className="text-[11px] font-semibold text-slate-500 uppercase">Issuing Department</span>
                <p className="text-sm font-bold text-slate-900 mt-0.5">
                  {analysis.issuingOrganization.department || analysis.issuingOrganization.name}
                </p>
                <p className="text-xs text-slate-500 mt-0.5">
                  {analysis.issuingOrganization.jurisdiction || 'State Authority'}
                </p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80">
                <span className="text-[11px] font-semibold text-slate-500 uppercase">Primary Deadline</span>
                <p className="text-sm font-bold text-amber-900 mt-0.5">
                  {analysis.deadlines[0]?.date || 'See deadlines tab'}
                </p>
                <p className="text-xs text-slate-500 mt-0.5">
                  {analysis.deadlines[0]?.label || 'Submission cutoff'}
                </p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80">
                <span className="text-[11px] font-semibold text-slate-500 uppercase">Submission Mode</span>
                <p className="text-sm font-bold text-slate-900 mt-0.5 uppercase">
                  {analysis.applicationInstructions.mode}
                </p>
                <p className="text-xs text-slate-500 mt-0.5 truncate">
                  {analysis.applicationInstructions.portalUrl || 'Office Counter'}
                </p>
              </div>
            </div>
          </div>

          {/* Quick Action Plan Preview */}
          <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-base font-bold text-slate-900">Immediate Citizen Next Steps</h3>
                <p className="text-xs text-slate-500">What you should do first to comply with this notice</p>
              </div>
              <button
                onClick={() => setActiveTab('checklist')}
                className="text-xs font-semibold text-amber-700 hover:text-amber-800 flex items-center gap-1"
              >
                <span>View Full Checklist</span>
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>

            <div className="space-y-2.5">
              {analysis.actionChecklist.slice(0, 3).map((step) => {
                const isChecked = Boolean(completedSteps[step.stepNumber]);
                return (
                  <div
                    key={step.stepNumber}
                    onClick={() => toggleStep(step.stepNumber)}
                    className="flex items-start gap-3 p-3 rounded-xl border border-slate-200 hover:border-slate-300 hover:bg-slate-50/60 cursor-pointer transition-all"
                  >
                    <button className="mt-0.5 text-slate-500 hover:text-amber-600">
                      {isChecked ? (
                        <CheckSquare className="w-4 h-4 text-emerald-600" />
                      ) : (
                        <Square className="w-4 h-4 text-slate-400" />
                      )}
                    </button>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <span
                          className={`text-xs font-bold ${
                            isChecked ? 'line-through text-slate-400' : 'text-slate-900'
                          }`}
                        >
                          Step {step.stepNumber}: {step.title}
                        </span>
                        <span className="text-[10px] font-semibold uppercase text-slate-500">
                          {step.priority} Priority
                        </span>
                      </div>
                      <p
                        className={`text-xs mt-0.5 ${
                          isChecked ? 'line-through text-slate-400' : 'text-slate-600'
                        }`}
                      >
                        {step.description}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* 2. ACTION CHECKLIST TAB */}
      {activeTab === 'checklist' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
            <div>
              <h3 className="text-lg font-bold text-slate-900">{t.actionChecklistTab}</h3>
              <p className="text-xs text-slate-500">
                Check off items as you complete them. Progress is stored locally in your session.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-xs font-semibold text-slate-700">
                {completedCount} of {totalSteps} Completed ({progressPercent}%)
              </span>
              <button
                onClick={handleCopyChecklist}
                className="px-3 py-1.5 rounded-lg text-xs font-medium bg-amber-50 hover:bg-amber-100 text-amber-900 border border-amber-200 transition-colors"
              >
                {copyFeedback ? t.checklistCopied : t.copyChecklist}
              </button>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
            <div
              className="bg-emerald-500 h-full transition-all duration-300"
              style={{ width: `${progressPercent}%` }}
            />
          </div>

          {/* Steps List */}
          <div className="space-y-3">
            {analysis.actionChecklist.map((step) => {
              const isChecked = Boolean(completedSteps[step.stepNumber]);
              return (
                <div
                  key={step.stepNumber}
                  onClick={() => toggleStep(step.stepNumber)}
                  className={`p-4 rounded-xl border transition-all cursor-pointer ${
                    isChecked
                      ? 'bg-slate-50/80 border-slate-200'
                      : 'bg-white border-slate-200 hover:border-slate-300 hover:shadow-2xs'
                  }`}
                >
                  <div className="flex items-start gap-3.5">
                    <button className="mt-0.5 text-slate-500 hover:text-amber-600">
                      {isChecked ? (
                        <CheckSquare className="w-5 h-5 text-emerald-600" />
                      ) : (
                        <Square className="w-5 h-5 text-slate-400" />
                      )}
                    </button>
                    <div className="flex-1">
                      <div className="flex flex-wrap items-center justify-between gap-2 mb-1">
                        <h4
                          className={`text-sm font-bold ${
                            isChecked ? 'line-through text-slate-400' : 'text-slate-900'
                          }`}
                        >
                          Step {step.stepNumber}: {step.title}
                        </h4>
                        <div className="flex items-center gap-2">
                          <span
                            className={`text-[10px] font-semibold px-2 py-0.5 rounded uppercase ${
                              step.priority === 'high'
                                ? 'bg-rose-50 text-rose-700 border border-rose-200'
                                : step.priority === 'medium'
                                ? 'bg-amber-50 text-amber-700 border border-amber-200'
                                : 'bg-slate-100 text-slate-700'
                            }`}
                          >
                            {step.priority} Priority
                          </span>
                          <span className="text-[10px] font-medium text-slate-500 bg-slate-100 px-2 py-0.5 rounded uppercase">
                            {step.category}
                          </span>
                        </div>
                      </div>
                      <p
                        className={`text-xs leading-relaxed ${
                          isChecked ? 'line-through text-slate-400' : 'text-slate-600'
                        }`}
                      >
                        {step.description}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* 3. DEADLINES & TIMELINE TAB */}
      {activeTab === 'deadlines' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-5">
          <div>
            <h3 className="text-lg font-bold text-slate-900">{t.deadlinesTab}</h3>
            <p className="text-xs text-slate-500">
              Crucial cutoffs extracted from the circular. Download calendar events (.ics) to avoid missing deadlines.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {analysis.deadlines.map((dl, idx) => (
              <div
                key={idx}
                className="p-4 rounded-xl border border-slate-200 bg-white hover:border-slate-300 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase ${
                        dl.urgency === 'urgent'
                          ? 'bg-rose-100 text-rose-800 border border-rose-200'
                          : dl.urgency === 'upcoming'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                          : dl.urgency === 'passed'
                          ? 'bg-slate-200 text-slate-700'
                          : 'bg-amber-100 text-amber-800'
                      }`}
                    >
                      {dl.urgency}
                    </span>
                    {dl.time && (
                      <span className="text-xs text-slate-500 flex items-center gap-1">
                        <Clock className="w-3 h-3" /> {dl.time}
                      </span>
                    )}
                  </div>
                  <h4 className="text-sm font-bold text-slate-900 mb-1">{dl.label}</h4>
                  <div className="text-lg font-extrabold text-amber-900 mb-2">{dl.date}</div>
                  <p className="text-xs text-slate-600">{dl.description}</p>
                </div>

                <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between">
                  <button
                    onClick={() => handleCalendarExport(dl)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-amber-800 bg-amber-50 hover:bg-amber-100 transition-colors"
                  >
                    <CalendarPlus className="w-3.5 h-3.5" />
                    <span>{t.addToCalendar}</span>
                  </button>
                  <span className="text-[11px] text-slate-400">Strictly extracted date</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 4. REQUIRED DOCUMENTS TAB */}
      {activeTab === 'documents' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-5">
          <div>
            <h3 className="text-lg font-bold text-slate-900">{t.documentsTab}</h3>
            <p className="text-xs text-slate-500">
              Certificates, IDs, and records required for submission or physical verification.
            </p>
          </div>

          <div className="space-y-3">
            {analysis.requiredDocuments.map((doc, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl border border-slate-200 bg-slate-50/50 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-sm font-bold text-slate-900">{doc.documentName}</span>
                    <span
                      className={`text-[10px] font-semibold px-2 py-0.5 rounded uppercase ${
                        doc.mandatory
                          ? 'bg-rose-50 text-rose-700 border border-rose-200'
                          : 'bg-slate-100 text-slate-600'
                      }`}
                    >
                      {doc.mandatory ? 'Mandatory' : 'Optional / If Applicable'}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600">{doc.notes}</p>
                </div>
                {doc.formatRequired && (
                  <span className="text-xs font-medium text-slate-700 bg-white px-2.5 py-1 rounded-lg border border-slate-200 whitespace-nowrap self-start sm:self-auto">
                    Format: {doc.formatRequired}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 5. ELIGIBILITY TAB */}
      {activeTab === 'eligibility' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-6">
          <div>
            <h3 className="text-lg font-bold text-slate-900">{t.eligibilityTab}</h3>
            <p className="text-xs text-slate-500">
              Who qualifies, restrictions, income limits, and educational criteria.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-4 rounded-xl bg-emerald-50/60 border border-emerald-200">
              <h4 className="text-xs font-bold text-emerald-900 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Who Can Apply / Eligible Categories
              </h4>
              <ul className="space-y-2 text-xs text-emerald-950 font-medium">
                {analysis.eligibility.whoCanApply.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="text-emerald-600 mt-0.5">•</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-rose-50/60 border border-rose-200">
              <h4 className="text-xs font-bold text-rose-900 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-rose-600" />
                Exclusions / Ineligible Categories
              </h4>
              <ul className="space-y-2 text-xs text-rose-950 font-medium">
                {analysis.eligibility.whoCannotApply.length > 0 ? (
                  analysis.eligibility.whoCannotApply.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="text-rose-600 mt-0.5">•</span>
                      <span>{item}</span>
                    </li>
                  ))
                ) : (
                  <li className="text-slate-500 italic">No explicit exclusions stated in the notice.</li>
                )}
              </ul>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-slate-100">
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">Annual Income Ceiling</span>
              <p className="text-sm font-bold text-slate-900 mt-1">
                {analysis.eligibility.incomeLimit || 'Not specified in notice'}
              </p>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">Educational / Academic Criteria</span>
              <p className="text-sm font-bold text-slate-900 mt-1">
                {analysis.eligibility.educationalCriteria || 'Not specified in notice'}
              </p>
            </div>
          </div>

          {/* Application Mode & Contact strip */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-3">
            <h4 className="text-xs font-bold text-slate-900 uppercase">{t.howToApply}</h4>
            <div className="space-y-1.5 text-xs text-slate-700">
              {analysis.applicationInstructions.steps.map((st, i) => (
                <p key={i}>
                  <span className="font-semibold">{i + 1}.</span> {st}
                </p>
              ))}
            </div>

            {analysis.applicationInstructions.portalUrl && (
              <div className="pt-2 flex items-center gap-2 text-xs">
                <span className="font-semibold text-slate-700">Official Portal:</span>
                <a
                  href={analysis.applicationInstructions.portalUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-amber-700 underline font-medium flex items-center gap-1 hover:text-amber-800"
                >
                  {analysis.applicationInstructions.portalUrl}
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
            )}
          </div>
        </div>
      )}

      {/* 6. TRUST & SAFETY AUDIT TAB */}
      {activeTab === 'trust' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-6">
          <div>
            <h3 className="text-lg font-bold text-slate-900">{t.trustSafetyTab}</h3>
            <p className="text-xs text-slate-500">
              Forensic breakdown distinguishing strictly extracted document facts from general advice.
            </p>
          </div>

          {/* Authenticity Indicators */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">Official Seal</span>
              <p className="text-sm font-bold text-slate-900 mt-1">
                {analysis.trustAndSafety.sealDetected ? 'Detected on Image' : 'Not Visible'}
              </p>
              <p className="text-xs text-slate-500 mt-0.5">
                {analysis.trustAndSafety.sealDetails || 'None detected'}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">Authorized Signature</span>
              <p className="text-sm font-bold text-slate-900 mt-1">
                {analysis.trustAndSafety.signatureDetected ? 'Signature Identified' : 'No Signature Visible'}
              </p>
              <p className="text-xs text-slate-500 mt-0.5">
                {analysis.trustAndSafety.signatoryDesignation || 'None detected'}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">Document Legibility</span>
              <p className="text-sm font-bold text-emerald-800 mt-1 uppercase">
                {analysis.trustAndSafety.documentIntegrity}
              </p>
              <p className="text-xs text-slate-500 mt-0.5">
                Model confidence: {analysis.trustAndSafety.confidenceScore}%
              </p>
            </div>
          </div>

          {/* Tri-Part Distinction (Trust & Safety Rule) */}
          <div className="space-y-4 pt-2">
            <div className="p-4 rounded-xl bg-emerald-50/70 border border-emerald-200">
              <h4 className="text-xs font-bold text-emerald-900 uppercase mb-2 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                {t.strictFacts}
              </h4>
              <ul className="space-y-1.5 text-xs text-emerald-950 font-medium">
                {analysis.trustAndSafety.extractedVsVerifiedDistinction.strictlyExtractedFromDocument.map(
                  (f, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-emerald-600">•</span>
                      <span>{f}</span>
                    </li>
                  )
                )}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-blue-50/70 border border-blue-200">
              <h4 className="text-xs font-bold text-blue-900 uppercase mb-2 flex items-center gap-1.5">
                <Info className="w-4 h-4 text-blue-600" />
                {t.contextualNotes}
              </h4>
              <ul className="space-y-1.5 text-xs text-blue-950">
                {analysis.trustAndSafety.extractedVsVerifiedDistinction.contextualNotesFromKnowledge.map(
                  (n, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-blue-600">•</span>
                      <span>{n}</span>
                    </li>
                  )
                )}
              </ul>
            </div>

            {analysis.trustAndSafety.extractedVsVerifiedDistinction.unverifiedClaims.length > 0 && (
              <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200">
                <h4 className="text-xs font-bold text-amber-900 uppercase mb-2 flex items-center gap-1.5">
                  <ShieldAlert className="w-4 h-4 text-amber-600" />
                  {t.unverifiedClaims}
                </h4>
                <ul className="space-y-1.5 text-xs text-amber-950">
                  {analysis.trustAndSafety.extractedVsVerifiedDistinction.unverifiedClaims.map(
                    (u, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <span className="text-amber-600">•</span>
                        <span>{u}</span>
                      </li>
                    )
                  )}
                </ul>
              </div>
            )}
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-500">
            <span className="font-semibold text-slate-700">Notice Disclaimer: </span>
            {analysis.trustAndSafety.disclaimer}
          </div>
        </div>
      )}

      {/* 7. ASK GEMMA 4 TAB */}
      {activeTab === 'qa' && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs space-y-6">
          <div>
            <h3 className="text-lg font-bold text-slate-900">Ask Gemma 4 About This Notice</h3>
            <p className="text-xs text-slate-500">
              Gemma 4 will inspect the uploaded notice image and answer your specific citizen question without guessing.
            </p>
          </div>

          {/* Question Form */}
          <form onSubmit={handleAskQuestion} className="flex items-center gap-2">
            <input
              type="text"
              value={qaQuestion}
              onChange={(e) => setQaQuestion(e.target.value)}
              placeholder="e.g. Can final year engineering students apply? Is there a fee concession?"
              className="flex-1 px-4 py-2.5 rounded-xl border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-amber-500/50"
              disabled={qaLoading}
            />
            <button
              type="submit"
              disabled={qaLoading || !qaQuestion.trim()}
              className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-amber-700 hover:bg-amber-800 disabled:opacity-50 text-white font-semibold text-sm transition-all"
            >
              <Send className="w-4 h-4" />
              <span>{qaLoading ? 'Analyzing...' : 'Ask'}</span>
            </button>
          </form>

          {/* Quick Prompts */}
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <span className="text-slate-400">Try asking:</span>
            {[
              'Are original documents required or only copies?',
              'What is the last date to avoid late fine?',
              'Where is the physical submission office?',
            ].map((prompt, i) => (
              <button
                key={i}
                onClick={() => setQaQuestion(prompt)}
                className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-[11px] transition-colors"
              >
                {prompt}
              </button>
            ))}
          </div>

          {/* Q&A Thread History */}
          <div className="space-y-4 pt-4 border-t border-slate-100">
            {qaHistory.length === 0 ? (
              <p className="text-xs text-slate-400 text-center py-6">
                No questions asked yet. Ask any clarification about this circular above!
              </p>
            ) : (
              qaHistory.map((item, idx) => (
                <div key={idx} className="space-y-2 p-4 rounded-xl bg-slate-50 border border-slate-200">
                  <div className="flex items-center justify-between text-xs font-bold text-slate-900">
                    <span>Citizen Question:</span>
                    <span className="text-slate-400 font-normal">{item.time}</span>
                  </div>
                  <p className="text-sm text-slate-800 font-medium">{item.q}</p>
                  <div className="pt-2 border-t border-slate-200/80">
                    <span className="text-[11px] font-bold text-amber-800 uppercase flex items-center gap-1 mb-1">
                      <Sparkles className="w-3 h-3 text-amber-600" />
                      Gemma 4 Answer:
                    </span>
                    <p className="text-xs text-slate-700 leading-relaxed whitespace-pre-wrap">
                      {item.a}
                    </p>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
};
