import { NoticeDeadline } from '../types/notice';

/**
 * Parses diverse Indian date formats into a Date object or safe fallback
 */
function parseIndianDate(dateStr: string): Date {
  const now = new Date();
  if (!dateStr || dateStr.toLowerCase().includes('not')) return now;

  // DD-MM-YYYY or DD/MM/YYYY
  const dmyMatch = dateStr.match(/(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})/);
  if (dmyMatch) {
    const [, day, month, year] = dmyMatch;
    return new Date(Number(year), Number(month) - 1, Number(day), 17, 0, 0);
  }

  // "15th November 2026" or "15 Nov 2026"
  const parsed = Date.parse(dateStr);
  if (!isNaN(parsed)) {
    return new Date(parsed);
  }

  return now;
}

function formatDateToIcs(d: Date): string {
  const pad = (n: number) => (n < 10 ? '0' + n : String(n));
  return (
    d.getUTCFullYear() +
    pad(d.getUTCMonth() + 1) +
    pad(d.getUTCDate()) +
    'T' +
    pad(d.getUTCHours()) +
    pad(d.getUTCMinutes()) +
    '00Z'
  );
}

export function downloadCalendarEvent(title: string, deadline: NoticeDeadline, issuer: string) {
  const startDate = parseIndianDate(deadline.date);
  const endDate = new Date(startDate.getTime() + 60 * 60 * 1000); // 1 hour event

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//NammaNotice AI//Hacktoberfest Hack Day Bengaluru//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `UID:${Date.now()}@nammanotice.ai`,
    `DTSTAMP:${formatDateToIcs(new Date())}`,
    `DTSTART:${formatDateToIcs(startDate)}`,
    `DTEND:${formatDateToIcs(endDate)}`,
    `SUMMARY:DEADLINE: ${title}`,
    `DESCRIPTION:${deadline.label} - ${deadline.description}\\nIssuing Authority: ${issuer}\\nGenerated by NammaNotice AI (Gemma 4)`,
    `STATUS:CONFIRMED`,
    'BEGIN:VALARM',
    'TRIGGER:-P1D',
    'ACTION:DISPLAY',
    `DESCRIPTION:Reminder: 1 Day before deadline for ${title}`,
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `NammaNotice_Deadline_${deadline.date.replace(/[^a-zA-Z0-9]/g, '_')}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
